# Generated by Django 4.0.4 on 2022-10-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='special',
            new_name='specialites',
        ),
    ]
